/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FaqBlock = {
  _type: "faqBlock";
  heading?: string;
  items?: Array<{
    _key: string;
  } & FaqItem>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageBlock = {
  _type: "imageBlock";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  altText?: string;
  caption?: string;
};

export type TextBlock = {
  _type: "textBlock";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type HeroBlock = {
  _type: "heroBlock";
  eyebrow?: string;
  heading?: string;
  subheading?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryCta?: Link;
  secondaryCta?: Link;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  internalRef?: PageReference;
  externalUrl?: string;
};

export type Seo = {
  _type: "seo";
  seoTitle?: string;
  seoDescription?: string;
  shareImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<{
    _key: string;
  } & HeroBlock | {
    _key: string;
  } & TextBlock | {
    _key: string;
  } & ImageBlock | {
    _key: string;
  } & FaqBlock>;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  announcement?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryNavigation?: Array<{
    _key: string;
  } & Link>;
  footerText?: string;
  socialLinks?: Array<{
    _key: string;
  } & Link>;
  contactEmail?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = FaqBlock | SanityImageAssetReference | ImageBlock | TextBlock | HeroBlock | FaqItem | PageReference | Link | Seo | Page | SanityImageCrop | SanityImageHotspot | Slug | SiteSettings | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../zeeks/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    _id,    title,    description,    announcement,    logo,    primaryNavigation[] {      _key,      label,      linkType,      externalUrl,      "internalSlug": internalRef->slug.current    },    footerText,    socialLinks[] {      _key,      label,      linkType,      externalUrl,      "internalSlug": internalRef->slug.current    },    contactEmail  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  title: string | null;
  description: string | null;
  announcement: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  primaryNavigation: Array<{
    _key: string;
    label: string | null;
    linkType: "external" | "internal" | null;
    externalUrl: string | null;
    internalSlug: string | null;
  }> | null;
  footerText: string | null;
  socialLinks: Array<{
    _key: string;
    label: string | null;
    linkType: "external" | "internal" | null;
    externalUrl: string | null;
    internalSlug: string | null;
  }> | null;
  contactEmail: string | null;
} | null;

// Source: ../zeeks/lib/sanity/queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    seo,    pageBuilder[] {      _key,      _type,      eyebrow,      heading,      subheading,      image,      primaryCta {        _key,        label,        linkType,        externalUrl,        "internalSlug": internalRef->slug.current      },      secondaryCta {        _key,        label,        linkType,        externalUrl,        "internalSlug": internalRef->slug.current      },      content,      altText,      caption,      items    }  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  seo: Seo | null;
  pageBuilder: Array<{
    _key: string;
    _type: "faqBlock";
    eyebrow: null;
    heading: string | null;
    subheading: null;
    image: null;
    primaryCta: null;
    secondaryCta: null;
    content: null;
    altText: null;
    caption: null;
    items: Array<{
      _key: string;
    } & FaqItem> | null;
  } | {
    _key: string;
    _type: "heroBlock";
    eyebrow: string | null;
    heading: string | null;
    subheading: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    primaryCta: {
      _key: null;
      label: string | null;
      linkType: "external" | "internal" | null;
      externalUrl: string | null;
      internalSlug: string | null;
    } | null;
    secondaryCta: {
      _key: null;
      label: string | null;
      linkType: "external" | "internal" | null;
      externalUrl: string | null;
      internalSlug: string | null;
    } | null;
    content: null;
    altText: null;
    caption: null;
    items: null;
  } | {
    _key: string;
    _type: "imageBlock";
    eyebrow: null;
    heading: null;
    subheading: null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    primaryCta: null;
    secondaryCta: null;
    content: null;
    altText: string | null;
    caption: string | null;
    items: null;
  } | {
    _key: string;
    _type: "textBlock";
    eyebrow: null;
    heading: null;
    subheading: null;
    image: null;
    primaryCta: null;
    secondaryCta: null;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    altText: null;
    caption: null;
    items: null;
  }> | null;
} | null;

// Source: ../zeeks/lib/sanity/queries.ts
// Variable: ALL_PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{ "slug": slug.current }
export type ALL_PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"siteSettings\"][0]{\n    _id,\n    title,\n    description,\n    announcement,\n    logo,\n    primaryNavigation[] {\n      _key,\n      label,\n      linkType,\n      externalUrl,\n      \"internalSlug\": internalRef->slug.current\n    },\n    footerText,\n    socialLinks[] {\n      _key,\n      label,\n      linkType,\n      externalUrl,\n      \"internalSlug\": internalRef->slug.current\n    },\n    contactEmail\n  }\n": SITE_SETTINGS_QUERY_RESULT;
    "\n  *[_type == \"page\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    seo,\n    pageBuilder[] {\n      _key,\n      _type,\n      eyebrow,\n      heading,\n      subheading,\n      image,\n      primaryCta {\n        _key,\n        label,\n        linkType,\n        externalUrl,\n        \"internalSlug\": internalRef->slug.current\n      },\n      secondaryCta {\n        _key,\n        label,\n        linkType,\n        externalUrl,\n        \"internalSlug\": internalRef->slug.current\n      },\n      content,\n      altText,\n      caption,\n      items\n    }\n  }\n": PAGE_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"page\" && defined(slug.current)]{ \"slug\": slug.current }\n": ALL_PAGE_SLUGS_QUERY_RESULT;
  }
}

